"""
The CC problem restated in RG language.
"""
import math

Lambda_obs = 1.06e-52
l_P = 1.616e-35

Lambda_natural = Lambda_obs * l_P**2

print("=" * 70)
print("THE CC PROBLEM IN RG LANGUAGE")
print("=" * 70)
print()
print("In natural units (hbar = c = 1):")
print("  G has units [M^-2], Lambda has units [M^2]")
print("  So G x Lambda is dimensionless at any scale k.")
print()
print("  At the FP: G~* x L~* = 0.12")
print("  So G(k) x L(k) = 0.12 at EVERY scale (if the product is constant).")
print()
print("  But G(k) x L(k) = G~(k) x L~(k) which RUNS with k.")
print("  It is only stationary at the FP.")
print()
print("OBSERVED:")
print("  L_obs = 1.06e-52 m^-2")
print("  G_N = 6.674e-11 m^3 kg^-1 s^-2")
print("  L_obs x G_N in Planck units = " + "{:.3e}".format(Lambda_natural))
print()
print("AT THE FP:")
print("  G~* x L~* = 0.12")
print("  G(Planck) x L(Planck) = 0.12")
print()
print("THE GAP:")
print("  FP prediction:     0.12")
print("  Observed:          " + "{:.3e}".format(Lambda_natural))
print("  Gap:               " + "{:.0e}".format(0.12 / Lambda_natural) + "x")
print()
print("WHAT THIS MEANS:")
print("  The product G~(k) x L~(k) must decrease by a factor of")
print("  " + "{:.0e}".format(0.12 / Lambda_natural) + " from the UV FP to the IR.")
print()
print("  This is the CC problem: why does the dimensionless product")
print("  run from 0.12 to 2.77e-122?")
print()
print("WHAT THE FP PREDICTS vs WHAT IT DOES NOT:")
print()
print("  VERIFIED (from Codello 2009):")
print("    UV FP values: G~* = 0.7012, L~* = 0.1715 (EH)")
print("    Product: G~* x L~* = 0.12 (scheme-independent)")
print("    Critical exponents: theta = 1.689 +/- 2.486i (EH)")
print("    Relevant directions: 2 (EH), 3 (f(R) at n>=4)")
print("    f(R) convergence: G~* = 0.95-0.99, L~* = 0.12-0.13")
print()
print("  NOT PREDICTED:")
print("    The value L_obs x G_N = 2.77e-122")
print("    The running of G~ x L~ from 0.12 to 2.77e-122")
print("    The individual values of L_obs and G_N")
print()
print("  THE HONEST CONCLUSION:")
print("    The FP provides the UV initial condition: G~* x L~* = 0.12")
print("    The observed value L_obs x G_N = 10^-122 is the IR boundary condition.")
print("    The path from 0.12 to 10^-122 is the RG flow, which requires the")
print("    FULL beta functions (beyond EH truncation) to compute.")
print("    This is the remaining open problem.")
