[pytest]
testpaths = tests
norecursedirs = archive archive/* sigma_venv sigma_venv/* *.venv *venv archive/New\ folder/improved/.venv Millennium-Prize-Problem-Lean-4-Proof archive/New\ folder/improved/.venv/Lib fcc2 archive/New folder/improved/.venv sigma_venv/Lib/site-packages
addopts = -q
python_files = test_*.py
python_classes = Test*
python_functions = test_*
