"""Generator script to write fr_beta_v2.py"""
import os

lines = []
def w(s=""):
    lines.append(s)

w('"""')
w("f(R) beta functions from Codello 2009 eq.(117)+(119).")
w("Evaluate PDE RHS at n+1 well-spaced R values, solve for Taylor coefficients.")
w("Iterate for self-consistent fp_dot/fpp_dot.")
w('"""')
w("import math")
w()
w("def flow_rhs(R, g, fp_dot_val=0.0, fpp_dot_val=0.0):")
w("    pi = math.pi")
w("    R2=R*R; R3=R2*R; R4=R3*R")
w("    f = sum(g[i]*R**i for i in range(len(g)))")
w("    fp = sum(i*g[i]*R**(i-1) for i in range(1,len(g)))")
w("    fpp = sum(i*(i-1)*g[i]*R**(i-2) for i in range(2,len(g)))")
w("    fppp = sum(i*(i-1)*(i-2)*g[i]*R**(i-3) for i in range(3,len(g)))")
w("    pf = 384.0*pi**2/30240.0")
w("    def sd(num,den): return num/den if abs(den)>1e-40 else 0.0")
w("    denT = 3*f-(R-3)*fp")
w("    numT = (20*(311*R3-126*R2-22680*R+45360)*(fp_dot_val+2*fp-2*R*fpp)")
w("            -252*(R2+360*R-1080)*fp)")
w("    Rm3sq = (R-3)**2")
w("    denS = fpp*Rm3sq+2*f+(3-2*R)*fp")
w("    numS = (1008*(29*R2+360*R+1080)*fp")
w("            +4*(185*R3+3654*R2+22680*R+45360)*(fp_dot_val+2*fp-2*R*fpp)")
w("            -2016*(29*R3+273*R2-3240)*fpp")
w("            -9*(181*R4+3248*R3+15288*R2-90720)*(fpp_dot_val-2*R*fppp))")
w("    Tpoles = -1008*(511*R2-360*R-1080)/(R-3) - 2016*(607*R2-360*R-2160)/(R-4)")
w("    Sig = sd(-10*(R2-20*R+54)*R2, R2-7*R+12)")
w("    return pf*(Tpoles + sd(numT,denT) + sd(numS,denS) + Sig)")
w()
w("def solve_lu(A, b):")
w("    n = len(b)")
w("    M = [row[:]+[b[i]] for i,row in enumerate(A)]")
w("    for c in range(n):")
w("        br = max(range(c,n), key=lambda r: abs(M[r][c]))")
w("        M[c],M[br] = M[br],M[c]")
w("        p = M[c][c]")
w("        if abs(p)<1e-40: continue")
w("        for r in range(c+1,n):")
w("            fac = M[r][c]/p")
w("            for j in range(c,n+1): M[r][j] -= fac*M[c][j]")
w("    x = [0.0]*n")
w("    for i in range(n-1,-1,-1):")
w("        s = M[i][n]")
w("        for j in range(i+1,n): s -= M[i][j]*x[j]")
w("        x[i] = s/M[i][i] if abs(M[i][i])>1e-40 else 0.0")
w("    return x")
w()
w("def extract_betas(g, nmax, R_eval=None):")
w("    n = nmax+1")
w("    if R_eval is None:")
w("        R_eval = [i*0.4 for i in range(n)]")
w("    A = [[Rj**k for k in range(n)] for Rj in R_eval]")
w("    Ainv_rows = []")
w("    for i in range(n):")
w("        ei = [0.0]*n; ei[i]=1.0")
w("        Ainv_rows.append(solve_lu(A, ei))")
w("    betas = [0.0]*n")
w("    for iteration in range(30):")
w("        fp_dots = []")
w("        fpp_dots = []")
w("        for Rj in R_eval:")
w("            fpd = sum(i*betas[i]*Rj**(i-1) for i in range(1,n))")
w("            fppd = sum(i*(i-1)*betas[i]*Rj**(i-2) for i in range(2,n))")
w("            fp_dots.append(fpd)")
w("            fpp_dots.append(fppd)")
w("        rhs = [flow_rhs(R_eval[j], g, fp_dots[j], fpp_dots[j]) for j in range(n)]")
w("        new_betas = [sum(Ainv_rows[i][j]*rhs[j] for j in range(n)) for i in range(n)]")
w("        mx = max(abs(new_betas[i]-betas[i]) for i in range(n))")
w("        betas = new_betas")
w("        if mx < 1e-25: break")
w("    return betas")
w()
w("def get_eval_points(n):")
w("    pts = []")
w("    for i in range(n):")
w("        x = i * 2.5 / max(n-1, 1)")
w("        if x > 2.8: x += 0.5")
w("        if x > 3.8: x += 0.5")
w("        pts.append(x)")
w("    return pts")
w()
w("def stability_matrix(g, nmax, eps=1e-7):")
w("    n = nmax+1")
w("    M = [[0.0]*n for _ in range(n)]")
w("    for j in range(n):")
w("        gp = list(g); gp[j]+=eps")
w("        gm = list(g); gm[j]-=eps")
w("        bp = extract_betas(gp, nmax)")
w("        bm = extract_betas(gm, nmax)")
w("        for i in range(n):")
w("            M[i][j] = (bp[i]-bm[i])/(2*eps)")
w("    return M")
w()
w("def eigenvalues_2x2(M):")
w("    tr = M[0][0]+M[1][1]")
w("    det = M[0][0]*M[1][1]-M[0][1]*M[1][0]")
w("    disc = tr*tr-4*det")
w("    if disc >= 0:")
w("        sq = math.sqrt(disc)")
w("        return [-(tr+sq)/2, -(tr-sq)/2]")
w("    else:")
w("        sq = math.sqrt(-disc)")
w("        return [complex(-tr/2, sq/2), complex(-tr/2, -sq/2)]")
w()
w("if __name__ == '__main__':")
w("    print('='*70)")
w("    print('f(R) BETA FUNCTIONS - SELF-CONSISTENT EXTRACTION')")
w("    print('='*70)")
w()
w("    fp_data = {")
w("        1: [5.226e-3, -20.140e-3],")
w("        2: [3.292e-3, -12.726e-3, 1.514e-3],")
w("        3: [5.184e-3, -19.596e-3, 0.702e-3, -9.682e-3],")
w("        4: [5.059e-3, -20.585e-3, 0.270e-3, -10.967e-3, -8.646e-3],")
w("    }")
w()
w("    for nmax in [1, 2, 3, 4]:")
w("        g_fp = fp_data[nmax]")
w("        n = nmax+1")
w("        Rpts = get_eval_points(n)")
w("        b = extract_betas(g_fp, nmax, Rpts)")
w("        res = math.sqrt(sum(x**2 for x in b))")
w("        strs = ', '.join('%.4e'%x for x in b)")
w("        print(f'n={nmax}: betas=[{strs}], residual={res:.4e}')")
w()
w("    print()")
w("    print('='*70)")
w("    print('STABILITY MATRIX (n=4)')")
w("    print('='*70)")
w("    g4 = fp_data[4]")
w("    M = stability_matrix(g4, 4, eps=1e-7)")
w("    for i in range(5):")
w("        row = ', '.join('%.4e'%M[i][j] for j in range(5))")
w("        print(f'  [{row}]')")
w()
w("    ev = eigenvalues_2x2(M[:2][:2])")
w("    print(f'First 2 eigenvalues: {ev}')")

content = '\n'.join(lines) + '\n'
with open(os.path.join(os.path.dirname(__file__) or '.', 'fr_beta_v2.py'), 'w') as f:
    f.write(content)
print("Wrote fr_beta_v2.py (%d lines)" % len(lines))
